### ISSUE TITLE
ofp_vs运行出错

### ISSUE THREAD

**Issue by Edward-L** [lvsgate/lvs-dpdk#7]
刚才把ofp_vs重新编译了下，跑了下，这是日志
`root@localhost ofp_vs]# ./ofp_vs -i 0,1 -c 2 -o 0 -p 1 -f ofp.conf
RLIMIT_CORE: 0/-1
Setting to max: 0

ODP system info
---------------
ODP API version: 1.14.0
CPU model:       
CPU freq (hz):   3407872000
Cache line size: 0
Core count:      0
Outer port:      0
Inner port:      1

Running ODP appl: "ofp_vs"
-----------------
IF-count:        2
Using IFs:       0 1

EAL: Detected 2 lcore(s)
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
EAL: PCI device 0000:02:01.0 on NUMA socket -1
EAL:   probe driver: 8086:100f net_e1000_em
EAL: PCI device 0000:02:01.0 on NUMA socket -1
EAL:   probe driver: 8086:100f net_e1000_em
EAL: PCI device 0000:02:05.0 on NUMA socket -1
EAL:   probe driver: 8086:100f net_e1000_em
EAL: PCI device 0000:02:06.0 on NUMA socket -1
EAL:   probe driver: 8086:100f net_e1000_em
../linux-generic/_ishmphy.c:150:_odp_ishmphy_map():mmap failed:Cannot allocate memory
../linux-generic/_ishm.c:866:_odp_ishm_reserve():No huge pages, fall back to normal pages. check: /proc/sys/vm/nr_hugepages.
../linux-generic/_ishmphy.c:150:_odp_ishmphy_map():mmap failed:Cannot allocate memory
../linux-generic/_ishmphy.c:150:_odp_ishmphy_map():mmap failed:Cannot allocate memory
../linux-generic/_ishmphy.c:150:_odp_ishmphy_map():mmap failed:Cannot allocate memory
 PKTIO: initialized loop interface.
../linux-generic/_ishmphy.c:150:_odp_ishmphy_map():mmap failed:Cannot allocate memory
No crypto devices available
../linux-generic/_ishmphy.c:150:_odp_ishmphy_map():mmap failed:Cannot allocate memory
../linux-generic/_ishmphy.c:150:_odp_ishmphy_map():mmap failed:Cannot allocate memory
odp_cpu_count : 2
Num worker threads: 1
first CPU:          1
cpu mask:           0x2
../linux-generic/_ishmphy.c:150:_odp_ishmphy_map():mmap failed:Cannot allocate memory
../linux-generic/_ishmphy.c:150:_odp_ishmphy_map():mmap failed:Cannot allocate memory
../linux-generic/_ishmphy.c:150:_odp_ishmphy_map():mmap failed:Cannot allocate memory
I 5 1:1536392960 ofp_uma.c:45] Creating pool 'udp_inpcb', nitems=1024 size=904 total=925696
I 5 1:1536392960 ofp_uma.c:45] Creating pool 'tcp_inpcb', nitems=2048 size=904 total=1851392
I 5 1:1536392960 ofp_uma.c:45] Creating pool 'tcpcb', nitems=2048 size=784 total=1605632
I 5 1:1536392960 ofp_uma.c:45] Creating pool 'tcptw', nitems=409 size=80 total=32720
I 5 1:1536392960 ofp_uma.c:45] Creating pool 'syncache', nitems=30720 size=168 total=5160960
I 6 1:1536392960 ofp_uma.c:45] Creating pool 'tcpreass', nitems=320 size=48 total=15360
I 6 1:1536392960 ofp_uma.c:45] Creating pool 'sackhole', nitems=65536 size=40 total=2621440
I 7 1:1536392960 ofp_init.c:245] Slow path threads on core 0
I 7 1:1536392960 ofp_ifnet.c:143] Device '0' addr  00:0c:29:7d:2e:ba
I 7 1:1536392960 ofp_ifnet.c:152] Device '0' MTU=1500
odp_thread.c:166:odp_thread_init_local():There is a thread already running on core 0
I 12 1:1536392960 main.c:369] if 0 rx_q 0 bind to cpu 1
I 12 1:1536392960 ofp_ifnet.c:143] Device '1' addr  00:0c:29:7d:2e:c4
I 12 1:1536392960 ofp_ifnet.c:152] Device '1' MTU=1500
odp_thread.c:166:odp_thread_init_local():There is a thread already running on core 0
odp_thread.c:166:odp_thread_init_local():There is a thread already running on core 0
odp_thread.c:166:odp_thread_init_local():There is a thread already running on core 0
I 16 1:1536392960 main.c:369] if 1 rx_q 0 bind to cpu 1
odp_thread.c:166:odp_thread_init_local():There is a thread already running on core 0
odp_thread.c:166:odp_thread_init_local():There is a thread already running on core 1
../linux-generic/odp_timer.c:687:timer_notify():
	1 ticks overrun on timer pool "TmrPool", timer resolution too high
I 20 1:1536392960 ofp_vs_ctl.c:3139] ofp_vs_ctl_init ok

I 20 1:1536392960 ofp_vs_proto.c:217] Registered protocols (TCP, UDP, ICMP)

Segmentation fault (core dumped)
`

**Comment by Edward-L** [comment]
odp_thread.c:166:odp_thread_init_local():There is a thread already running on core 0
I 13 1:4160610048 ofp_ifnet.c:143] Device '0' addr  00:0c:29:7d:2e:ba
I 13 1:4160610048 ofp_ifnet.c:152] Device '0' MTU=1500
Detaching after fork from child process 56194.
odp_thread.c:166:odp_thread_init_local():There is a thread already running on core 0
I 19 1:4160610048 main.c:369] if 0 rx_q 0 bind to cpu 1
I 19 1:4160610048 ofp_ifnet.c:143] Device '1' addr  00:0c:29:7d:2e:c4
I 19 1:4160610048 ofp_ifnet.c:152] Device '1' MTU=1500
odp_thread.c:166:odp_thread_init_local():There is a thread already running on core 0
odp_thread.c:166:odp_thread_init_local():There is a thread already running on core 0
I 24 1:4160610048 main.c:369] if 1 rx_q 0 bind to cpu 1
odp_thread.c:166:odp_thread_init_local():There is a thread already running on core 0
odp_thread.c:166:odp_thread_init_local():There is a thread already running on core 1
../linux-generic/odp_timer.c:687:timer_notify():
	1 ticks overrun on timer pool "TmrPool", timer resolution too high
I 28 1:4160610048 ofp_vs_ctl.c:3139] ofp_vs_ctl_init ok

I 28 1:4160610048 ofp_vs_proto.c:217] Registered protocols (TCP, UDP, ICMP)

[New Thread 0x7fff9ffff700 (LWP 56205)]

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff9ffff700 (LWP 56205)]
0x000000000041f5a3 in ofp_vs_timer_run (arg=0x0) at ofp_vs_timer.c:120
120		list_for_each_entry_safe(timer, timer_next,
(gdb) bt
#0  0x000000000041f5a3 in ofp_vs_timer_run (arg=0x0) at ofp_vs_timer.c:120
#1  0x000000000041f4ee in ofp_vs_rte_timer_cb (timer=0x703338 <rte_timer_array+120>, arg=0x0) at ofp_vs_timer.c:94
#2  0x0000000000473cb6 in rte_timer_manage ()
#3  0x0000000000408016 in event_dispatcher (arg=0x6d2720 <appl_params>) at main.c:232
#4  0x00007ffff6e235ba in _odph_run_start_routine (arg=0x7fffffffd6e8) at linux/thread.c:37
#5  0x00007ffff5e81dc5 in start_thread (arg=0x7fff9ffff700) at pthread_create.c:308
#6  0x00007ffff5bb076d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113
